### ISSUE TITLE
Error when creating room: TypeError: this.groom_items is undefined

### ISSUE THREAD

**Issue by sloria** [hlcfan/pokrex-chrome-extension#1]
# Steps

1. Click the extension button
2. Attempt to create a room.

# Expected

A room is created.

# Actual

A room is not created; no feedback is given.

An error occurs appears in the console.

# Screenshot

![image](https://user-images.githubusercontent.com/2379650/51133912-26b76600-1804-11e9-9abf-c9b26cb92800.png)

# Browser info

Firefox 64.0.2 on macOS 10.14.2 (Mojave)

**Comment by sloria** [comment]
The `TypeError` seems to happen if there are no tickets in the queue.

If there are tickets in the queue, I get a different error:

![image](https://user-images.githubusercontent.com/2379650/51134524-b6e9b100-17ec-11e9-80d1-d22ec35b493a.png)

**Comment by hlcfan** [comment]
Thanks for the feedback @sloria.

What's the extension version you're on? The latest is 1.2.

**Comment by sloria** [comment]
I was using 1.2.

**Comment by hlcfan** [comment]
Steve, please give it a shot if you have time, should be fixed on FF and Chrome both.

**Comment by sloria** [comment]
I'm not in charge of ticket grooming any more so I won't need to do this for a while, but I'll try when I have some free time.

**Comment by sloria** [comment]
Yep, looks fixed. Thanks!

**Comment by hlcfan** [comment]
Thanks 😁
